#!/usr/bin/env bash

#------------------------------------------------------------------------------
# @file
# Performs assertion testing of the functions in this library.
#
# This simple testing mechanism has no provision for the construction and
# deconstruction of unit test scaffolding.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Declares assertions.
#
# @return global array $assertions
#   This is a one dimensional array. Each element is a pipe delimited list
#   of three values in this sequence:
#
#   1. Function to test (example: bfl::join)
#   2. Parameters to pass to function (example, "1" "2" "3")
#   3. Expected return code (example: 0)
#------------------------------------------------------------------------------
declare_assertions() {
  declare -ga assertions=(
    'bfl::find_nearest_integer||1'
    'bfl::find_nearest_integer|"" "" ""|1'
    'bfl::find_nearest_integer|"" ""|1'
    'bfl::find_nearest_integer|" " " "|1'
    'bfl::find_nearest_integer|"a" ""|1'
    'bfl::find_nearest_integer|"1" ""|1'
    'bfl::find_nearest_integer|"1" " "|1'
    'bfl::find_nearest_integer|"1" "a e g"|1'
    'bfl::find_nearest_integer|"1.1" "4 -1 0 1 4"|1'
    'bfl::find_nearest_integer|"1" "4.1 -1 0 1 4"|1'
    'bfl::find_nearest_integer|"-2" "-4 -1 0 1 4"|0'
    'bfl::find_nearest_integer|"0" "-4 -1 0 1 4"|0'
    'bfl::find_nearest_integer|"2" "-4 -1 0 1 4"|0'

    'bfl::is_integer||1'
    'bfl::is_integer|""|1'
    'bfl::is_integer|" "|1'
    'bfl::is_integer|"foo"|1'
    'bfl::is_integer|"1.2"|1'
    'bfl::is_integer|"1" "2" "3"|1'
    'bfl::is_integer|"-1"|0'
    'bfl::is_integer|"1"|0'

    'bfl::is_positive_integer||1'
    'bfl::is_positive_integer|""|1'
    'bfl::is_positive_integer|" "|1'
    'bfl::is_positive_integer|"foo"|1'
    'bfl::is_positive_integer|"1.2"|1'
    'bfl::is_positive_integer|"1" "2" "3"|1'
    'bfl::is_positive_integer|"-1"|1'
    'bfl::is_positive_integer|"1"|0'
  )
