#!/usr/bin/env bash

#------------------------------------------------------------------------------
# @file
# Performs assertion testing of the functions in this library.
#
# This simple testing mechanism has no provision for the construction and
# deconstruction of unit test scaffolding.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Declares assertions.
#
# @return global array $assertions
#   This is a one dimensional array. Each element is a pipe delimited list
#   of three values in this sequence:
#
#   1. Function to test (example: bfl::join)
#   2. Parameters to pass to function (example, "1" "2" "3")
#   3. Expected return code (example: 0)
#------------------------------------------------------------------------------
declare_assertions() {
  declare -ga assertions=(
#   bfl::ssh_file_exists
#   If FILE exists on HOST, the function should return 0
    'bfl::ssh_file_exists|"/etc/hosts" "localhost"|0'
#   If FILE does not exist on HOST, the function should return 1
    'bfl::ssh_file_exists|"/12345" "my-fake-host"|1'
#   If HOST is inaccessible, the function should return an error code
#    'bfl::ssh_file_exists|"/etc/hosts" "my-fake-host"|>0'
    )
  }
