#!/usr/bin/env bash

#------------------------------------------------------------------------------
# @file
# Performs assertion testing of the functions in this library.
#
# This simple testing mechanism has no provision for the construction and
# deconstruction of unit test scaffolding.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Declares assertions.
#
# @return global array $assertions
#   This is a one dimensional array. Each element is a pipe delimited list
#   of three values in this sequence:
#
#   1. Function to test (example: bfl::join)
#   2. Parameters to pass to function (example, "1" "2" "3")
#   3. Expected return code (example: 0)
#------------------------------------------------------------------------------
declare_assertions() {
  declare -ga assertions=(
#   bfl::is_blank
    'bfl::is_blank||1'
    'bfl::is_blank|""|0'
    'bfl::is_blank|" "|0'
    'bfl::is_blank|"\t"|0'
    'bfl::is_blank|"\n"|0'
    'bfl::is_blank|"asd"|1'
#   bfl::join
    'bfl::join||1'
    'bfl::join|","|1'
    'bfl::join|"," "This is" "a" "test."|0'
    'bfl::join|"," "Foo"|0'
    'bfl::join|"" "Foo"|0'
    'bfl::join|"" "" ""|0'
    'bfl::join|"," ""|0'
    'bfl::join|"," "" ""|0'
    'bfl::join|"" ""|0'
#   bfl::repeat
    'bfl::repeat||1'
    'bfl::repeat|"" "" ""|1'
    'bfl::repeat|"" ""|1'
    'bfl::repeat|"" " "|1'
    'bfl::repeat|"" "a"|1'
    'bfl::repeat|"" "1.1"|1'
    'bfl::repeat|"" "-1"|1'
    'bfl::repeat|"" "3"|0'
    'bfl::repeat|" " "3"|0'
    'bfl::repeat|"-" "3"|0'
#   bfl::transliterate
    'bfl::transliterate||1'
    'bfl::transliterate|"This is A string." "So is this."|1'
    'bfl::transliterate|""|0'
    'bfl::transliterate|"This is A string."|0'
#   bfl::trim
    'bfl::trim||1'
    'bfl::trim|""|0'
    'bfl::trim|"abc"|0'
    'bfl::trim|"   def"|0'
    'bfl::trim|"ghi   "|0'
    'bfl::trim|"   jkl   "|0'
    'bfl::trim|"   mno   pqr   stu   "|0'
#   bfl::escape_special_symbols
#   Should return STRING with all special characters escaped
    'bfl::escape_special_symbols|"foo"|"foo"'
    'bfl::escape_special_symbols|"foo\"|"foo\\"'
    'bfl::escape_special_symbols|"f\$oo"|"f\\\$oo"'
    'bfl::escape_special_symbols|""|""'
  )
