#!/usr/bin/env bash

#------------------------------------------------------------------------------
# @file
# Repeats a string N times.
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Displays usage message.
#
# @return string $msg
#   The usage message.
#------------------------------------------------------------------------------
usage() {
  declare msg
  msg="
    Repeats a string N times.

    Usage:    $(basename "$0") string multiplier

    Example:  $(basename "$0") \"=\" \"10\"
  "
  msg=$(bfl::trim "${msg}") || bfl::die "Error: unable to trim usage message."
  printf "%s\\n" "${msg}"
  exit 1
}

#------------------------------------------------------------------------------
# @function
# Main function.
#
# shellcheck disable=1090
#------------------------------------------------------------------------------
main() {
  if ! source "${BASH_FUNCTION_LIBRARY}"; then
    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
    exit 1
  fi

  bfl::declare_global_display_constants
  bfl::verify_arg_count "$#" 2 2 || usage

  declare -r string_to_repeat="$1"
  declare -r multiplier="$2"
  declare repeated_string

  repeated_string=$(bfl::str_repeat "${string_to_repeat}" "${multiplier}") || bfl::die
  printf "%s" "${repeated_string}"
}

set -euo pipefail
main "$@"
