#!/usr/bin/env bash

#------------------------------------------------------------------------------
# @file
# Does something. #TODO
#
# Detailed description. #TODO
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# @function
# Displays usage message.
#
# @return string $msg
#   The usage message.
#------------------------------------------------------------------------------
usage() {
  declare msg
  msg="
    One sentence description. # TODO

    Detailed description (optional). Use multiple lines if needed. # TODO

    Usage:    $(basename "$0") arg1 arg2 # TODO

    Example:  $(basename "$0") \"foo\" \"bar\" # TODO
  "
  msg=$(bfl::trim "${msg}") || bfl::die "Error: unable to trim usage message."
  printf "%s\\n" "${msg}"
  exit 1
}

#------------------------------------------------------------------------------
# @function
# Performs cleanup when script exits for any reason. Called by trap.
#------------------------------------------------------------------------------
cleanup() {
  : #TODO
}

#------------------------------------------------------------------------------
# @function
# Main function.
#
# @param type $foo #TODO
#   Description. #TODO
# @param type $foo #TODO
#   Description. #TODO
#
# @return type $bar #TODO
#   Description. Remove this section nothing is returned. #TODO
#
# shellcheck disable=1090
#------------------------------------------------------------------------------
main() {
  if ! source "${BASH_FUNCTION_LIBRARY}"; then
    printf "Error: unable to source BASH_FUNCTION_LIBRARY.\\n"
    exit 1
  fi

  bfl::declare_global_display_constants
  bfl::verify_arg_count "$#" 2 2 || usage

  declare -r arg1="$1"
  declare -r arg2="$2"

  printf "%s %s\\n" "${arg1}" "${arg2}"
}

set -euo pipefail
trap cleanup EXIT
main "$@"
